name: Unit

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '^1.20', '^1.19', '~1.18', '~1.17', '~1.16', '~1.15', '~1.14', '~1.13', '~1.12' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
    
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
  
      - name: Run Race tests
        run: |
          go test --race
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
    
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.20"

      - name: Run tests with Coverage report
        run: |
          go test -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
